# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service.yaml
namespace: demo-prd
# Remove commonLabels - it interferes with Argo Rollouts

images:
- name: ghcr.io/breezepatel/demo-app-repo/demo-app
  newTag: '{{ .Freight.Artifacts[0].Version }}'
