apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service.yaml
namespace: demo-prd
commonLabels:
  environment: prd
images:
- name: ghcr.io/breezepatel/demo-app-repo/demo-app
  newTag: '1.0.0'  # This will be updated by Kargo promotions
